image: Visual Studio 2017

before_build:
  - nuget restore JsonEnvVar.sln

configuration:
  - Release

build:
  project: JsonEnvVar.sln
  publish_nuget: true

nuget:
  disable_publish_on_pr: true

deploy:
  - provider: NuGet
    api_key:
      secure: 1E0gLtabwrgzICTiFhi7eIneYRYYZu2miYaDWfa+OO5JtpInf1fiQ2oFtZfbtVAN
    on:
      branch: master